### ISSUE TITLE
Error running "rapidgame prebuild"

### ISSUE THREAD

**Issue by Samanosuke31** [NatWeiss/RapidGame#1]
Hi, I'm trying to prebuild RapidGame Libraries, but I'm getting the following error: 

Happily prebuilding 
Writing build log to: /Users/miguelc/Library/Developer/RapidGame/build.log
Copying /usr/local/lib/node_modules/rapidgame/src to /Users/miguelc/Library/Developer/RapidGame/src

/usr/local/lib/node_modules/rapidgame/node_modules/download/index.js:70
            if (opts.extract && decompress.canExtract(opts.url, mime)) {
                                           ^
TypeError: Object function Decompress() {
    this.ware = new Ware();
} has no method 'canExtract'
    at Request.<anonymous> (/usr/local/lib/node_modules/rapidgame/node_modules/download/index.js:70:44)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onResponse (/usr/local/lib/node_modules/rapidgame/node_modules/download/node_modules/request/request.js:924:10)
    at ClientRequest.g (events.js:175:14)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1669:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:120:23)
    at Socket.socketOnData [as ondata] (http.js:1564:20)
    at TCP.onread (net.js:525:27)

can you help me with that? I'm using OSX 10.9.

Thank you.

**Comment by NatWeiss** [comment]
Hey sorry it took me soooooooo long to reply! I didn't have notifications turned on for some reason.

It looks like the 'download' node module is missing a method for you. Can you tell me what version of download is installed for your rapidgame installation?

You might be able to fix it by changing your package.json:

"download": "~0.1.16",

=>

"download": "0.1.16",

That will tell it to use exactly version 0.1.16, which is the version I used to write rapidgame with. You might have to do `npm update download` after that.

Let me know how it goes.

**Comment by vinceferro** [comment]
Hi,
seems like cocos has moved the .zip, I fixed it by changing the cocos2djsUrl to http://cdn.cocos2d-x.org/cocos2d-js-v3.2.zip

**Comment by NatWeiss** [comment]
Thanks for catching this! I've updated the Github repo and node package.

**Comment by siba2893** [comment]
Hi Guys, I'm having the same problem but I did change the "download": "0.1.16", and I did the npm update download but it doesn't work

**Comment by NatWeiss** [comment]
Hmm. Well you could work around it by manually downloading cocos2d-js v3.2 and then extracting it to RapidGame/src/cocos2d-js. Then run prebuild and it ought to not even attempt the download. Let me know how it goes.

**Comment by lifeisdream** [comment]
Hi, could you help me a little bit please? i'm trying to run 'rapidgame create cocos2dx "HeckYeah" org.myorg.heckyeah' and ive got these messages. why this build fails? (win 7, ms vs 2012 ultimate)

-----
Static libraries must be prebuilt
Happily prebuilding
Writing build log to: C:\Users\owl\AppData\Roaming\npm\node_modules\rapidgame\build.log
Downloading http://cdn.cocos2d-x.org/cocos2d-js-v3.6.zip...
Download + extract finished
Moving C:/Users/owl/AppData/Roaming/npm/node_modules/rapidgame/src/cocos2d-js-v3.6 to C:\Users\owl\AppData\Roaming\npm\n
ode_modules\rapidgame\src\cocos2d-js
Applying patch file: C:\Users\owl\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d.patch
Copying header files...
Checking version = 2 against highest 0
Checking version = 3.5 against highest 2
Checking version = 4 against highest 3.5
Final MSBuildToolsPath: C:\Windows\Microsoft.NET\Framework\v4.0.30319\
Building Windows Debug cocos2d-win32.vc2012.sln...
Succeeded.
Building Windows Debug libJSBinding.vcxproj...
exec error: Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""lib.exe" /NOLOGO /IGNORE:4006 "/OUT:C:\Users\owl\
AppData\Roaming\npm\node_modules\rapidgame\0.9.7\cocos2d\x\lib\Debug-win32\x86\libcocos2dx-prebuilt.lib" C:\Users\owl\Ap
pData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\Debug.win32\*.lib C:\U
sers\owl\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\bindings\proj.win32\Debug.win3
2\*.lib C:\Users\owl\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\ed
itor-support\spine\proj.win32\Debug.win32\*.lib C:\Users\owl\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\f
rameworks\js-bindings\cocos2d-x\external\Box2D\proj.win32\Debug.win32\*.lib C:\Users\owl\AppData\Roaming\npm\node_module
s\rapidgame\src\cocos2d-js\frameworks\js-bindings\external\spidermonkey\prebuilt\win32\*.lib C:\Users\owl\AppData\Roamin
g\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\external\websockets\prebuilt\win32\*.lib"
""lib.exe"" ?? ?????? ???????? ??? ?????
????????, ??????? ?????? ??? ???????? ????.


""lib.exe"" ?? ?????? ???????? ??? ?????
????????, ??????? ?????? ??? ???????? ????.

{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""lib.exe" /NOLOGO /IGNORE:4006 "/OUT:C:\Users\owl\AppData\R
oaming\npm\node_modules\rapidgame\0.9.7\cocos2d\x\lib\Debug-win32\x86\libcocos2dx-prebuilt.lib" C:\Users\owl\AppData\Roa
ming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\Debug.win32\*.lib C:\Users\owl\
AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\bindings\proj.win32\Debug.win32\*.lib C
:\Users\owl\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\editor-supp
ort\spine\proj.win32\Debug.win32\*.lib C:\Users\owl\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks
\js-bindings\cocos2d-x\external\Box2D\proj.win32\Debug.win32\*.lib C:\Users\owl\AppData\Roaming\npm\node_modules\rapidga
me\src\cocos2d-js\frameworks\js-bindings\external\spidermonkey\prebuilt\win32\*.lib C:\Users\owl\AppData\Roaming\npm\nod
e_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\external\websockets\prebuilt\win32\*.lib"
""lib.exe"" ?? ?????? ???????? ??? ?????
????????, ??????? ?????? ??? ???????? ????.
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c ""lib.exe" /NOLOGO /IGNORE:4006 "/OUT:C:\\Users\\owl\\AppData\\Roaming\\npm
\\node_modules\\rapidgame\\0.9.7\\cocos2d\\x\\lib\\Debug-win32\\x86\\libcocos2dx-prebuilt.lib" C:\\Users\\owl\\AppData\\
Roaming\\npm\\node_modules\\rapidgame\\src\\cocos2d-js\\frameworks\\js-bindings\\cocos2d-x\\cocos\\2d\\Debug.win32\\*.li
b C:\\Users\\owl\\AppData\\Roaming\\npm\\node_modules\\rapidgame\\src\\cocos2d-js\\frameworks\\js-bindings\\bindings\\pr
oj.win32\\Debug.win32\\*.lib C:\\Users\\owl\\AppData\\Roaming\\npm\\node_modules\\rapidgame\\src\\cocos2d-js\\frameworks
\\js-bindings\\cocos2d-x\\cocos\\editor-support\\spine\\proj.win32\\Debug.win32\\*.lib C:\\Users\\owl\\AppData\\Roaming\
\npm\\node_modules\\rapidgame\\src\\cocos2d-js\\frameworks\\js-bindings\\cocos2d-x\\external\\Box2D\\proj.win32\\Debug.w
in32\\*.lib C:\\Users\\owl\\AppData\\Roaming\\npm\\node_modules\\rapidgame\\src\\cocos2d-js\\frameworks\\js-bindings\\ex
ternal\\spidermonkey\\prebuilt\\win32\\*.lib C:\\Users\\owl\\AppData\\Roaming\\npm\\node_modules\\rapidgame\\src\\cocos2
d-js\\frameworks\\js-bindings\\cocos2d-x\\external\\websockets\\prebuilt\\win32\\*.lib"' }
