### ISSUE TITLE
Device orientation

### ISSUE THREAD

**Issue by nanocore** [NatWeiss/RapidGame#10]
Have you looked into how code could be added to each of the device specific files that would generate a device orientation event (even a EventCustom event).  This could then be listened by the shared c++ code in the projects directory. That way the shared code ciuld handle device orientation changes in a single place.  And to be clear this is more then just the initial device orientation but any rotation of the device would trigger an event.

**Comment by nanocore** [comment]
I added the code, at least to the iOS side and will see how to mimic the same type of solution for the android side (if I can ever get it to actually compile).

**Comment by NatWeiss** [comment]
Thanks for the suggestion and sorry I missed your previous comment from 2 weeks ago.
