### ISSUE TITLE
Android build error libz

### ISSUE THREAD

**Issue by l0gg3r** [NatWeiss/RapidGame#11]
After running make on android project, I get 

Davids-MacBook-Pro:android david$ make
ANDROID_SDK_ROOT=/Users/david/Library/Android/sdk
PLUGIN_DIR=/Users/david/Desktop/Solitaire/lib/cocos2d/x/java
export CONFIG="debug" && ./build_native.py
The Selected NDK toolchain version was 4.8 !
Android NDK: WARNING: APP_PLATFORM android-18 is larger than android:minSdkVersion 10 in ./AndroidManifest.xml    
APP_PLATFORM=android-18
APP_OPTIM=debug
CONFIG=Debug
ARCH=armeabi
APP_CPPFLAGS=-frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DCOCOS2D_JAVASCRIPT -DCOCOS2D_DEBUG=1
make[1]: Entering directory `/Users/david/Desktop/Solitaire/Projects/android'
[armeabi] SharedLibrary  : libcocos2djs.so
/Users/david/Desktop/Solitaire/Projects/android/../../lib/cocos2d/x/java/mk/cocos2d-x/external/png/prebuilt/android/armeabi/libpng.a(pngrutil.o):pngrutil.c:function png_inflate_claim: error: undefined reference to 'inflateReset2'
/Users/david/Desktop/Solitaire/Projects/android/../../lib/cocos2d/x/java/mk/cocos2d-x/external/png/prebuilt/android/armeabi/libpng.a(pngrutil.o):pngrutil.c:function png_decompress_chunk.constprop.5: error: undefined reference to 'inflateReset2'
collect2: error: ld returned 1 exit status
make[1]: *** [obj/local/armeabi/libcocos2djs.so] Error 1
make[1]: Leaving directory `/Users/david/Desktop/Solitaire/Projects/android'
Traceback (most recent call last):
  File "./build_native.py", line 179, in <module>
    build(opts.ndk_build_param,opts.android_platform,opts.build_mode)
  File "./build_native.py", line 166, in build
    do_build(cocos_root, ndk_root, app_android_root,ndk_build_param,sdk_root,android_platform,build_mode)
  File "./build_native.py", line 90, in do_build
    raise Exception("Build dynamic library for project [ " + app_android_root + " ] fails!")
Exception: Build dynamic library for project [ /Users/david/Desktop/Solitaire/Projects/android ] fails!
make: *** [all] Error 1

Seems libz and libpng are not compatible.

**Comment by l0gg3r** [comment]
Issue is caused, because Android.mk LOCAL_WHOLE_STATIC_LIBRARIES doesn't include cocos_zlib_static.

After changing
<pre>
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_png_static cocos_jpeg_static cocos_tiff_static cocos_webp_static \
	cocos_curl_static cocos_freetype2_static spidermonkey_static websockets_static cocos_chipmunk_static
</pre>
to

<pre>
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_png_static cocos_jpeg_static cocos_tiff_static cocos_webp_static \
	cocos_curl_static cocos_freetype2_static spidermonkey_static websockets_static cocos_chipmunk_static \
	cocos_zlib_static
</pre>
Build passes.

**Comment by NatWeiss** [comment]
Thanks for the fix. Will add this to the next release.
