### ISSUE TITLE
Cannot open input file "libbox2d.lib"

### ISSUE THREAD

**Issue by Irtanib** [NatWeiss/RapidGame#16]
Please help me interpret this error.

         Debug.win32\SpritePolygon.obj
         Debug.win32\SpritePolygonCache.obj
         "C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\external\Box2D\proj.win32\Debug.win32\libbox2d.lib"
         "C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\editor-support\spine\proj.win32\Debug.win32\libSpine.lib"
     2>LINK : fatal error LNK1181: cannot open input file 'libbox2d.lib' [C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\libcocos2d.vcxproj]
     2>Done Building Project "C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\libcocos2d.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\bindings\proj.win32\libJSBinding.vcxproj" (default targets) -- FAILED.

Build FAILED.

       "C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\bindings\proj.win32\libJSBinding.vcxproj" (default target) (1) ->
       "C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\libcocos2d.vcxproj" (default target) (2) ->
       (Link target) -> 
         LINK : fatal error LNK1181: cannot open input file 'libbox2d.lib' [C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\libcocos2d.vcxproj]

**Comment by NatWeiss** [comment]
The linker is complaining that it is missing the file `libbox2d.lib`.

More info is needed in order to help you:

1. What project are you building? Or is this the RapidGame prebuild?
2. What version of RapidGame are you using?
3. If you are prebuilding RapidGame, what are you using to run the `rapidgame prebuild` command? Like cmd.exe, cygwin, cmder, etc...?

**Comment by NatWeiss** [comment]
You could try this:

1. Complete erasing your `C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame` folder.
2. Make sure you have git for Windows and make sure it is accessible via cmd.exe.
3. Install the latest rapidgame: `npm install rapidgame -g`
4. Prebuild: `rapidgame prebuild`

**Comment by NatWeiss** [comment]
#2 above is very important in order for RapidGame to patch cocos2d-x correctly so that it can be built from the command line. Else, it will give you the error with the missing `libbox2d.lib`.

**Comment by Irtanib** [comment]
1. prebuild
2. 0.9.9
3. cmd.exe

You're right.. cmd.exe said 'git' is not recognized as an internal or external command...

I'll try reinstalling git tonight.

**Comment by samoersnaes** [comment]
Hi, don't mean to intrude and cause any confusion, but if you have git installed, it could be that you just don't have in it your PATH. After you add git to your path (for me it's in `C:\Program Files (x86)\Git\cmd`), then follow the steps that Nathan suggested and everything should work :)

**Comment by Irtanib** [comment]
I added git to my PATH, and performed steps 1-4.  It recognizes git now, so thats good, but I'm still getting:

          LINK : fatal error LNK1181: cannot open input file 'libbox2d.lib' [C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\libcocos2d.vcxproj]

    63 Warning(s)
    1 Error(s)

It may be having trouble loading the patch files since earlier in the log this is recorded:

fatal: can't open patch 'C:\Users\Jamie': No such file or directory
Build started 6/17/2015 9:23:31 PM.

It's having trouble directing git to my username file (since I carelessly put spaces instead of underscores into my username).  I'll try on another username.

**Comment by Irtanib** [comment]
Under a new username (admin) I made it much farther.  This time it failed at:

Building Android undefined...
Spawn error Error: spawn make ENOENT
Build failed. Please run with --verbose...

The log ended with this statement repeated about 20 times:

websockets.lib(websockets.dll) : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library

**Comment by NatWeiss** [comment]
Good that it was just the spaces which caused the issue with your previous build. I think the following ought to fix it. If you change line 443 of rapidgame.js to this:

`exec("git apply --whitespace=nowarn " + '"' + src + '"', {cwd: dest, env: process.env}, function(err){`

That will wrap the git command with double quotes and hopefully will make it work with the spaces.

Regarding the second issue, you currently have to build Android on Windows using Cygwin (see the readme). Cmd.exe just won't do it. It sounds like it successfully built the Windows version of RapidGame though, so you can create a project now with `rapidgame create` and just ignore the fact that the Android build failed.

**Comment by samoersnaes** [comment]
Unfortunately, after the Android build was fixed for Windows, I added Android prebuilding to the default behavior when you run `rapidgame create cocos2dx` or `rapidgame create cocos2djs` for the first time, so if you're just trying to prebuild the libraries for Windows, you will always run into this error. I'll add this note to the Windows Notes in the README, as this behavior is intentional. Nathaneal's also patched the spacing issue with git so this won't occur in the next version. But first, I'll see if I can find some way to check what shell the user is running in and change the behavior.

Anyway Irtanib, if you haven't already, try building the default project you created in Visual Studio (open up `[NAME]\Projects\windows\[NAME].sln`)! It should build now seeing as you apparently didn't get any errors when prebuilding the Windows libraries. You can find the executable file after building the project in `[NAME]\Projects\windows\Debug.32\[NAME].exe`, or in `Release.32` if you set it to release mode.

**Comment by samoersnaes** [comment]
* `Debug.win32` or `Release.win32`

**Comment by samoersnaes** [comment]
Just to let you know, RapidGame will not longer attempt to prebuild the Android libraries in the next release if you're running it in cmd.exe :)

**Comment by Irtanib** [comment]
There must be another place in the code that needs double quotes because I'm still getting the

LINK : fatal error LNK1181: cannot open input file 'C:\Users\Jamie'

after fixing the line in the .js file.

**Comment by Irtanib** [comment]
I tried building a game on the alt account which prebuilt properly.  These are the errors VS reports:

![image](https://cloud.githubusercontent.com/assets/12928446/8228879/403476de-1580-11e5-9031-4a1996234d4b.png)

Looks like I just need to find and copy the cocos2d.h and CCStdC.h files.  Is that expected?

Thank you both for your help in this.  It'll be a HUGE timesaver when I get my settings right. :)

**Comment by samoersnaes** [comment]
Can you try running `rapidgame prebuild headers`? After that, try re-building the project.

P.S. Don't ask how long it took me to realize that might work :) I wasted a good 20 minutes writing up something else.

**Comment by samoersnaes** [comment]
Basically what I think is going on is somehow the header files weren't properly setup. If you find rapidgame (Nathanael mentioned its path early on in the comments) and then go to `0.9.9\cocos2d\x\include\cocos`, you should see for example cocos2d.h at the bottom.

**Comment by NatWeiss** [comment]
Regarding the link error and spaces, this might fix it. Line 886 of rapidgame.js:

`command += ' "' + path.join(libDirs[i], "*.lib") + '"';`

That will wrap the command which combines all the lib files with double quotes.

**Comment by Irtanib** [comment]
@samoersnaes I ran rapidgame prebuild headers; built a new project "proto2" and rebuilt it getting the same errors.

I just verified cocos2d.h is in the 0.9.9\cocos2d\x\include\cocos folder.

@NatWeiss I changed the command += line and got the same errors.

I don't need to run rapidgame prebuild after each new game creation do I?  I have been just in case, but it didn't make a difference.

**Comment by NatWeiss** [comment]
Nope, you don't need to run the prebuild each time after creating a game. Just once.

Any chance you could email me the build.log file which has the linker / space-related error? I'm nat [at] wizardfu [dot] com.

**Comment by Irtanib** [comment]
absolutely

**Comment by samoersnaes** [comment]
Okay, Nathanael sent me the build logs as well and had a really good suggestion.

If you open up `rapidgame.js` again, there's something on line 837 we'd like you to change. Currently it looks like this for you:

`'"/OUT:' + path.join(dest, "libcocos2dx-prebuilt.lib") + '"';`

If you change the line to this:

`'"/OUT:' + '"' + path.join(dest, "libcocos2dx-prebuilt.lib") + '"' + '"';`

Save and close, and try again, maybe we'll get lucky and it will work!

Also make sure you're running cmd.exe as administrator.

**Comment by Irtanib** [comment]
That fixed the inability to find .h files, so the 5 prior errors are fixed. Progress :).  1 new error:

Error	22	error LNK1104: cannot open file 'libcocos2dx-prebuilt.lib'	C:\Users\Jamie and Susannah_2\proto6\Projects\windows\LINK	proto6

**Comment by Irtanib** [comment]
It works beautifully on my alt username!

**Comment by samoersnaes** [comment]
Awesome!!! It's extremely unreasonably late here, so I'll see if I can find where that most recent error is occurring tomorrow, but good to hear you have something working :)

**Comment by Irtanib** [comment]
Understood, and yes I'm up and running on my alt username!!! :+1: 

I just tried rapidgame prebuild (normal username) since I frankly couldn't remember if it ever ran properly on my normal username and got a new error:

LNK 1181: cannot open input file 'and'

It seems my username "Jamie and Susannah_2" has really put your code through the ringer.

Thank you again for all your help in this regard.  Your rapid responses and follow through have been outstanding.  Thanks again.

**Comment by NatWeiss** [comment]
Ok, I took a closer look at one of the earlier build logs and found this (apparently successful) line:

`...link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\Jamie and Susannah_2\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\Debug.win32\libcocos2d.dll"`

It appears that the double quote needs to start directly after the `/OUT:` and not before. Can you try this one last change? Instead of the previous fix, can you try this:

`'/OUT:"' + path.join(dest, "libcocos2dx-prebuilt.lib") + '"';`

Subtle change to move the double quote to directly after the colon, but hopefully it makes all the difference.

**Comment by Irtanib** [comment]
No luck

**Comment by NatWeiss** [comment]
Well, I guess we need better log output. If you have a chance, can you try adding this to the `exec()` function around line 1317?

Was:

	if (cmd.verbose) {
		console.log(command);
		console.log("Current dir: " + options.cwd);
	}

Change to:

	if (cmd.verbose) {
		console.log(command);
		console.log("Current dir: " + options.cwd);
	} else {
		logBuild("\nExecuting:\n\t" + command + "\nCurrent dir:\n\t" + options.cwd + "\n");
	}
