### ISSUE TITLE
Prebuild cocos2dx fails

### ISSUE THREAD

**Issue by ferologics** [NatWeiss/RapidGame#17]
Once finished with mac and iOS it fails, dos it have to do anything with me not having android NDK? thx

Building iOS Release iphonesimulator cocos2dx-prebuilt...
Succeeded.
Building Android Debug armeabi...
Build failed. Please run with --verbose or check the build log: /Users/Macbook/Library/Developer/RapidGame/build.log

here's the verbose output - 

Building Android Debug armeabi...
/Users/Macbook/Library/Developer/RapidGame/src/proj.android/build.sh armeabi Debug
Current dir: /Users/Macbook/Library/Developer/RapidGame/src/proj.android
util.print: Use console.log instead
PLATFORM=android-18
ARCH=armeabi
util.print: Use console.log instead
CONFIG=Debug
util.print: Use console.log instead
CORES=4
util.print: Use console.log instead
Please set the NDK_ROOT environment variable.

**Comment by samoersnaes** [comment]
Hey there!

When you run `rapidgame prebuild`, the command tries to build the libraries for every platform it can, and the order on Mac is Mac, iOS, then Android. The build for Android does indeed require some extra tools like you said before you can prebuild the Android-specific libraries. However, if you don't want to target your game for Android, you don't have to worry about it, as the Mac and iOS libraries have already been prebuilt on your computer (you can create a test project and try it out).

If you do want to develop for Android, we have a [README](https://htmlpreview.github.io/?https://github.com/NatWeiss/RapidGame/blob/master/templates/cocos2dx/TwoScene/Projects/android/README.html#tl-dr) specifically for that, because there are a lot of programs you need to download and configure that are specific to Android development. After you download the Android tools, just run `rapidgame prebuild android` and your project should now be able to build for Android :)

Let me know if you need anymore help.

**Comment by ferologics** [comment]
I'm actually going for mac first so rapidgame prebuild mac works super duper for me

But I still have confusions because the code isnt there when I pseudo sign to my jb iphone, it basically crashes and the app size is 8,something size and the cocos2dx libraries themselves are 300+megabites... weird

**Comment by samoersnaes** [comment]
Yeah, that's odd. I'm not that involved on the Mac side of things so I'm not familiar with the workflow of building an app (I did years ago, but I haven't touched it recently). Nathanael is also on vacation for another week I believe. He would definitely have a better idea what to do than me.

In any case, could you send me some screenshots so I can see what's going on? You can upload them to [Imgur](http://imgur.com/) if you're comfortable with them being publicly viewable (although no one's really going to see them).

**Comment by ferologics** [comment]
dropbox copies it to my clipboard... Idk if that warning can affect anything, probably not..

the mac version works just fine and has the same size btw...

here's a file with links to dropbox photos http://pastie.org/10275503

**Comment by samoersnaes** [comment]
Hey again.

Sorry for the delay this time. I was out in town.

Anyway, I looked over the screenshots. I was wondering, could you send me screenshots of what the Xcode project recognizes? And by crashing do you mean getting a black or something and exiting back to the home screen? Also, just to be clear, my understanding is the Mac project builds and runs, but the iOS one doesn't. Let me know if I misinterpreted what you said.

Btw, it's okay that the project size is 8.6MB. It's 1.5MB on my machine before I build anything. The library files also appear to be a good size. I have the Windows and Android libraries prebuilt for all configurations and that's nearly 1GB of stuff. Could I ask you to check `RapidGame/0.9.9/cocos2d/x/lib` and expand all the folders to see what's in there? You can find the RapidGame folder `~/Library/Developer/RapidGame` here on Mac.

**Comment by ferologics** [comment]
Crashing - it just goes straight to home screen

Both projects build and run but the one on iphone doesn't work, the mac one works fine

Screens - http://pastie.org/private/ehquvulmqewmlnhceaufug

**Comment by samoersnaes** [comment]
Have you only attempted to run the project on the iOS Simulator and not on an actual device? Or have you tried both? I'm curious whether it works on a physical device.

Maybe there is some extra requirement after building the app to get it running? I remember back when I tried iOS development that I had to get an account and do stuff with bundle identifiers and key signing, and I had to go in the settings on my old iPod Touch to get the app on my device. It's similar for Android.

Would you mind if we did a brief Skype or Google Hangouts session? It's easier for me to get the bigger picture when I can ask you do to something in real time. If we can't troubleshoot it within at most an hour, I think you might have to wait until Nathanael returns from vacation unfortunately, as I don't have a Mac to try and recreate the problem on (I could see if I could find the time in the next couple days if it gets to that point).

But yeah, let me know if you wouldn't mind Skyping or something :) There's a chance we could get it up and running pretty quickly.

**Comment by ferologics** [comment]
The previous screenshot was from device and yes I tried thats what is my current problem. Add me on skype - ferko.hetes

**Comment by ferologics** [comment]
SOLVED IT. I don't know why xcode built the .app for iOS Simulator, I changed it to iOS Device and then everything worked like a charm.

Thx mate, maybe skype later if I find another problem with rapidgame lol ;))

**Comment by samoersnaes** [comment]
Sweet! Glad everything works. And yeah, sounds good :)
