### ISSUE TITLE
Initial project warning

### ISSUE THREAD

**Issue by ferologics** [NatWeiss/RapidGame#18]
I built the project and got following warning - 

--------
warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in _jinit_arith_decoder from /Users/Macbook/Library/Developer/RapidGame/0.9.9/cocos2d/x/lib/Debug-iOS/iphoneos/libcocos2dx-prebuilt.a(jdarith.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
--------

- [screenshot](https://www.dropbox.com/s/ls8t26tjhypgqbt/Screenshot%202015-07-06%2020.58.34.png?dl=0) - 

how can I make this go away? 

found [this post](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/issues/35) but i don't know how this translates for rapidgame :/

**Comment by samoersnaes** [comment]
Not a lot of time since I have to leave soon. Will be back in 5 hours max.

1. Did you build in debug or release mode? Can you try building with the mode you haven't used before and see what happends?
2. [This]https://developer.apple.com/library/ios/qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354) may help, but I'm not certain, as it seems the iOS library itself contains code that isn't PIE.
3. It's a warning so still see if it runs :) If it does, great! You only need to make sure your app is PIE when you submit it to the App Store (from what I just read). I'll make sure to bug Nathanael about it when he gets back. I looked briefly through the build script that builds the actual iOS libraries and I couldn't find anything there that shouldn't be there at first glance, but it could be the case that its lacking an option that it should have.

**Comment by samoersnaes** [comment]
* [This](https://developer.apple.com/library/ios/qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

**Comment by samoersnaes** [comment]
Okay, so apparently the quickest fix would be to toggle the "Don't Create Position Independent Executables" in the project's build settings. If you change it from NO to YES, your app should build without any warnings.

This is of course temporary, as you want your app to be PIE (meaning it can launch and run in any valid point of memory without issue), and Apple recommends this in their submission guidelines. So if you want to get rid of the warning for now, try the above. When Nathanael gets back, he can take a look at it closer and see if we need to add a compiler flag for example when building the iOS libraries.

**Comment by ferologics** [comment]
Yeaa, it says not to use some flags so... Thx, at least I dont have to look at it atm, it's not like it's a pressing matter so I'll hapilly wait

**Comment by samoersnaes** [comment]
Okay! We'll keep the issue open until we work it out.

**Comment by NatWeiss** [comment]
@samoersnaes thanks for you help as always.

@ferologics Well, I have gotten this PIE warning in the past for a different project and was able to fix it somehow... Too bad I cannot remember more details about it currently.

I took a look at all the information you provided, especially the link to the github coversation regarding fixing it in cocos2d-x. I even tried a new RapidGame 0.9.9 created project and it is weird but my system doesn't duplicate the issue. I'm sorry, but I don't have any helpful information or a solution at this time.

Just for the record, do you get the warning when you build and run for the iOS simulator?

**Comment by ferologics** [comment]
ATM I'm not able to check if the warning still persists as my laptop got stolen, I'll be raising money for a new one hopefully, to finish work on my app (it's going to be huge), lol, and after that I can give you feedback on the warning in the game project I'm doing, in the meantime I'm kinda powerless :/

**Comment by samoersnaes** [comment]
Please tell me you have some way of remoting into your machine :)

**Comment by ferologics** [comment]
I had find my mac on it, locked it but I don't think that it'll be found (...San Francisco...), everything important is either in my dropbox or github, my phone and tablet so it's kinda ok I guess but still it was a very recent macbook air, loved it

**Comment by samoersnaes** [comment]
Sorry about that :/ It may be possible to get access and install a keylogger or take some pics through the webcam and send the info to the police.

**Comment by ferologics** [comment]
yea, but so far it didn't connect to the internet so i suppose that it's already in parts somewhere.. Otherwise I'd get notified about the location of the laptop

**Comment by samoersnaes** [comment]
That's no fun. Well, good luck with getting the funds for a new laptop!

**Comment by ferologics** [comment]
thanks man :) I hope people will be able to relate and see that I can bring them value through my app (a hackathon tracking/sharing app in short)

**Comment by NatWeiss** [comment]
This ought to be fixed in the new version (0.9.12) as it defaults to building x86_64 for the iPhone Simulator.

Closing this issue for now. Feel free to reopen if necessary.
