### ISSUE TITLE
`rapidgame prebuild [platform]` doesn't actually limit prebuilding to the platform

### ISSUE THREAD

**Issue by chadmoore** [NatWeiss/RapidGame#2]
~ rapidgame prebuild android
    Happily prebuilding android
    Writing build log to: /Users/chadm/Library/Developer/RapidGame/build.log
    Copying /usr/local/lib/node_modules/rapidgame/src to /Users/chadm/Library/Developer/RapidGame/src
    Building iOS Debug iphoneos cocos2dx-prebuilt...
    Succeeded.
    Building iOS Debug iphonesimulator cocos2dx-prebuilt... <cont..>

**Comment by NatWeiss** [comment]
Hey thanks for mentioning this and sorry I had notifications turned off somehow so I didn't notice your message till now.

The new version of RapidGame (0.9.0) does limit prebuilding to Android if specified.

**Comment by NatWeiss** [comment]
Closing this issue now. Feel free to re-open if it doesn't work for you.
