### ISSUE TITLE
cocos2d-js ?

### ISSUE THREAD

**Issue by jonnyijapan** [NatWeiss/RapidGame#20]
Might be something I overlooked but:

When I run rapidgame create cocos2dx "HeckYeah" org.myorg.heckyeah

it looks like it's downloading cocos2d-js-v3.6.zip ...
Does this mean I can only use JavaScript for developing?

My intention is to use C++, not JavaScript, so I was expecting it to download cocos2d-x for C++, not JS.

**Comment by jonnyijapan** [comment]
Found your answer which is:

"Good question. It might seem odd at first, but hopefully you'll see the advantages.

cocos2d-js includes the javascript bindings. Without them your cocos2d-x game cannot run any javascript. JS can be great for scripting levels and other stuff.

With cocos2d-js both JS and C++ games can be created. If one has cocos2d-js, they can create an HTML5 game, a purely Javascript-based native game, a mixture of both JS and C++ game, and/or a purely C++ game. With cocos2d-x only purely C++ games can be created."

**Comment by samoersnaes** [comment]
Hey there!

While most people won't encounter the problem you will, I'm still adding a note to the README so others can see. Check under the "Creating a game" session.

> Keep in mind if you are completely new to the cocos2d family that creating a cocos2d-x project (`rapidgame create cocos2dx`) means your project code will be in C++, while building a cocos2d-js project (`rapidgame create cocos2djs`) allows you to develop your game in Javascript as well as C++ if you wish.

Also, glad you figured it out on your own and good luck!
