### ISSUE TITLE
Maintaining source files

### ISSUE THREAD

**Issue by jonnyijapan** [NatWeiss/RapidGame#22]
The docs (at https://htmlpreview.github.io/?https://github.com/NatWeiss/RapidGame/blob/master/templates/cocos2dx/TwoScene/Projects/android/README.html#useful-tools ) state:

> You can create, delete, and edit source files under [APPNAME]/Projects and assets under [APPNAME]/Assets as you wish. Changes in these folders will be included in the Android build automatically.

However, when I delete GameScene.h/cpp, MenuScene.h/cpp, Game.h/cpp from Projects and add my own scenes (I have some from vanilla cocos2d-x), it still wants to use those classes (gamescene.cpp) from the template. I looked around and it seems like GameScene, MenuScene and Game are hardcoded into Android.mk, and it does not look like it adds files from Projects/ dynamically, or I missed something.

Also, the makeignore file seems to do nothing...

**Comment by jonnyijapan** [comment]
I notice a few things.

 The Android makefile I have looks different from the one in this repo.
And for instance there is no ./build_files.py in the Android template I have. And makefile never calls it in the "all" configuration. I think I (still?) have an old RapidGame version or something. I installed RapidGame using "sudo npm install rapidgame -g", is there another way?

**Comment by samoersnaes** [comment]
The Android README is written for the new version of RapidGame that we unfortunately haven't released yet, meaning the docs you read are inaccurate for now (until we release the new version).

There are however two ways you could get the Android project to compile:

1. Add you own files to `Android.mk` (`Projects/android/jni`). You do this by editing `LOCAL_SRC_FILES` on line 20 of the file. Make you you leave `main.cpp` alone, and each time you add or delete a file, you would have to manually edit `Android.mk` before running `make` again. An example would be:

> LOCAL_SRC_FILES := main.cpp \
> ../../my_file1.cpp \
> ../../my_file2.cpp

2. You could download `build_files.py`, `makefile`, and `makeignore` from [here](https://github.com/NatWeiss/RapidGame/tree/master/templates/cocos2dx/TwoScene/Projects/android) and include them in your `Projects/android` directory. After that, everything should work as noted in the docs. If you want to keep this functionality for every future project you create, you can add these files to `rapidgame/templates/cocos2dx/TwoScene/Projects/android` (you can find RapidGame in one of the directories I mentioned in the previous issue you had).

Hope this solves your issue! I'm closing this for now, but if you can't figure it out, send me another comment or re-open it if need-be.

**Comment by samoersnaes** [comment]
Also, let me know if it does work as well :)

**Comment by samoersnaes** [comment]
You can safely delete `project.json` as well from your project (only if you chose option 2).

**Comment by samoersnaes** [comment]
Oh sorry! If you decide to go with option 2, you should also download `build_native.py` from the same link I mentioned.
