### ISSUE TITLE
PRE-BUILDING ON WINDOWS

### ISSUE THREAD

**Issue by jafferton91** [NatWeiss/RapidGame#25]
Command prompt - 

Happily prebuilding windows
Writing build log to: C:\Users\Jesson\AppData\Roaming\npm\node_modules\rapidgame\build.log
key (inside func)=2.0
checking version = 2 against highest 0
key (inside func)=14.0
checking version = 14 against highest 2
key (inside func)=12.0
checking version = 12 against highest 14
key (inside func)=3.5
checking version = 3.5 against highest 14
key (inside func)=4.0
checking version = 4 against highest 14
Final MSBuildToolsPath: C:\Program Files (x86)\MSBuild\14.0\bin\
Building Windows Debug cocos2d-win32.vc2012.sln...
Succeeded.
Building Windows Debug libJSBinding.vcxproj...
Build failed. Please run with --verbose or check the build log: C:\Users\Jesson\AppData\Roaming\npm\node_modules\rapidgame\build.log

Error from the build log - 

C:\Users\Jesson\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\base/CCConsole.h(42): fatal error C1083: Cannot open include file: 'thread': No such file or directory [C:\Users\Jesson\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-js\frameworks\js-bindings\cocos2d-x\cocos\2d\libcocos2d.vcxproj]

I can't pre build rapidgame after installing, any ideas?

**Comment by NatWeiss** [comment]
Did you run as administrator?

**Comment by osro** [comment]
I'm having the same problem. The verbose mode outputs this ...

"error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools."

And I have Visual Studio 2015 installed.

**Comment by NatWeiss** [comment]
Are you able to compile the cocos2d-x test project with Visual Studio 2015? Last I heard cocos2d-x doesn't work with the 2015 version, but they may have fixed it as of 3.7.

**Comment by osro** [comment]
3.7 works fine at least, haven't tried 3.6. Rapidgame still uses 3.6 I guess?

**Comment by NatWeiss** [comment]
It did, yes. I just published version 0.9.10 that uses 3.7.

**Comment by NatWeiss** [comment]
Also, the newest version of RapidGame (now 0.9.11) allows you to manually set the path to the VCTargetsPath directory, which is likely related to the build tools path error you experienced. Just upgrade rapidgame (`npm update rapidgame -g`) then attempt to prebuild. If it fails you can navigate to `<username>\AppData\Roaming\npm\node_modules\rapidgame` and manually edit `vctargetspath.txt`.

Closing this issue for now. Feel free to reopen if needed.

**Comment by osro** [comment]
Nope, still same problem. Now (with 0.9.,11) it just gives error from v140 tools. 
Also all those paths in .txt files looks valid to me. Weird...

Here is the build.log 
http://pastebin.com/9pKE4VYQ

I'm running on Windows 10 if that matters anything.
I can also build template projects made with cocos console just fine.

**Comment by NatWeiss** [comment]
It looks like you need to manually edit your vctargetspath.txt. Maybe change it to v120?

**Comment by osro** [comment]
The path in vctargetspath.txt was actually already pointing to that
 
Now I changed msbuildpath to *14.0* from 12.0
"C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe"

And vctargetspath to *V140* from V120
"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\"

In both cases, 12.0 and V120, the folders and files are there, but for some reason it is not working.

But now when I open the Visual Studio project from the newly created rapidgame project it throws the same error

warning  : The build tools for Visual Studio 2010 (v100) cannot be found. To build using the Visual Studio 2015 (v140) build tools, either click the Project menu or right-click the solution, and then select "Upgrade Solution...". Install Visual Studio 2010 (v100) to build using the Visual Studio 2010 (v100) build tools.

I tried to upgrade the project to 2015 version, but I'm unable to build the template project as it gives some errors.

**Comment by NatWeiss** [comment]
Good. The prebuild is now working and it's an easy fix to get rapidgame.js to recognize 14.0 and v140. 

Next will be to fix the template project. Any chance you could post your template project's upgraded vcxproj file? It should have some lines that will detect and use the 14.0 version tools. Moreover, it should be backwards compatible. I will then take a look at the errors. Also can you tell me which errors you are getting? (Only the first few if you are getting lots of them.)

**Comment by osro** [comment]
https://dl.dropboxusercontent.com/u/1641946/rapidgame/TestProject.vcxproj

There is just error one at the beginning.

Error C2872 'Game': ambiguous symbol	TestProject c:\users\ossir\documents\projects\testproject\projects\appdelegate.cpp	62

That line is 
Game::setContentRect(contentRect);

I quickly tried to comment that line out, but then it will give you some more 

Error LNK1104	 cannot open file 'libpng-2015.lib' TestProject	C:\Users\ossir\Documents\Projects\TestProject\Projects\windows\LINK	1

**Comment by NatWeiss** [comment]
Thanks, will start working on the fixes. Here's instructions on how to fix those two errors if you like:

1. Comment out the `friend class Game` in `0.9.11\cocos2d\x\include\cocos\base\CCProperties.h`.
2. Copy all the `*-2015.lib` files from `src\cocos2d-x\build\Debug.win32` into `0.9.11\cocos2d\x\lib\Debug-win32\x86`.

**Comment by osro** [comment]
Ok, got it running.
There was file called libpng-2015.duplicate-lib. I renamed that to libpng-2015.lib

**Comment by NatWeiss** [comment]
Awesome!

**Comment by NatWeiss** [comment]
Fixes are checked in, tested and part of 0.9.12.
