### ISSUE TITLE
Rapidgame prebuild error: lib.exe

### ISSUE THREAD

**Issue by rmallermartins** [NatWeiss/RapidGame#26]
I'm having an error with the 'rapidgame prebuild' command. Here's the [FULL LOG](https://gist.github.com/rmallermartins/f1d517de0c3ac38d8310), my language is Portuguese-Brazil, but the error is: 

`'lib.exe' is not recognized as an internal or external command, an operable program or batch file`.

I tried editing the lines in the rapidgame.js where this command is created, adding and removing the '"', but none of the combinations worked. And found nothing in the internet saying how to add `lib.exe` to the the Windows PATH variable.

**Comment by NatWeiss** [comment]
Do you have Visual Studio installed?

Did you run as administrator?

**Comment by rmallermartins** [comment]
Yes, I've got to make a normal Cocos2d-x project work using the win32 Build in Visual Studio 2013. I'm pretty sure running as administrator, and tried to prebuild using both CMD and Cygwin, same error.

**Comment by NatWeiss** [comment]
The newest version of RapidGame (0.9.11) allows you to manually set the path to lib.exe. Just upgrade rapidgame (`npm update rapidgame -g`) then attempt to prebuild. It will fail to find the path to lib.exe and give you instructions on how to set it manually.

Closing this issue for now. Feel free to reopen if needed.
