### ISSUE TITLE
iOS Framework Linking

### ISSUE THREAD

**Issue by NatWeiss** [NatWeiss/RapidGame#27]
There is a potential issue reported by someone over email. After creating a RapidGame project, the following frameworks are possibly missing and need to be deleted then re-added to the iOS project.

MediaPlayer
GameController
Security
OpenGLES
UIKit
CoreMotion

To do: take a look at the raw `project.pbxproj` to see if these are pointing to the correct frameworks.

**Comment by seivan** [comment]
Actually, a better way to import these frameworks is to use the new import keyword e.g ```@import OpenGLES``` 

Btw thanks for a great tool, it really makes it easy to jump in to Cocos2d-X and almost as easy as Using SpriteKit directly in Xcode.

**Comment by NatWeiss** [comment]
Thanks, I wasn't aware of that new keyword. Does it break backward compatibility?

**Comment by seivan** [comment]
I think the backwards compatibility is based on the compiler (or in our case Xcode)

You have to be using Xcode 5 and the iOS 7 or Mavericks SDK, but you can still release for older OSs (say iOS 4.3 or whatever). Modules don't change how your code is built or any of the source code.
