### ISSUE TITLE
[Xcode 7] libcocos2d should not link with frameworks

### ISSUE THREAD

**Issue by seivan** [NatWeiss/RapidGame#28]
More info here http://discuss.cocos2d-x.org/t/how-to-compile-with-xcode-7/22677
From what I gather, RapidGame uses the Xcode Project from the Cocos2d-x repo and this probably requires a pull request on their end.

Would be cool, if RapidGame would accept a git url for any Cocos2d-x repo :)

**Comment by NatWeiss** [comment]
Actualy RapidGame maintains it's own template project separate from the cocos2d-x repo so this shouldn't be a problem to update.

I will get Xcode 7 and test it out...

Regarding git urls, RapidGame doesn't use them. It actually downloads one of cocos2d-x' release zip files, unzips, patches as needed, then compiles, links, merges, etc. Using git custom urls would be a maintenance nightmare (for me), as RapidGame already takes away valuable time from the game I'm currently working on.

**Comment by seivan** [comment]
Oh okay, so I could make a fork and npm install that to try it out? 
I can't seem to find the Xcode project that RapidGame use to compile Cocos2dx.a if you could point me to it I could try it out myself :)

**Comment by seivan** [comment]
From what I can tell the source project for compiling is http://cdn.cocos2d-x.org/cocos2d-x-3.7.zip
Are you saying that you use your own template project to compile cocos2dx into a static framework?

If you could point that out, I'd gladly try it out as well (and do a pull request)

**Comment by NatWeiss** [comment]
Yep, it does use a template project. It's in src/proj.ios_mac

**Comment by seivan** [comment]
From what I can tell, RapidGame still uses ```cocos2d_libs.xcodeproj``` to compile.
You essentially just copy the workspace/project to the ```src/proj.ios_mac``` and use it as a dependency.

The rules for compiling (e.g linking binaries)  are still inside  ```cocos2d_libs.xcodeproj```

Now, I went inside ```/usr/local/lib/node_modules/rapidgame/src```
and modified ```cocos2d_libs.xcodeproj``` to remove all linking binaries for both iOS and Mac Os target.

It worked.

```
Writing build log to: /usr/local/lib/node_modules/rapidgame/build.log
Happily prebuilding 
Copying header files...
Building Mac Debug macosx cocos2dx-prebuilt...
Succeeded.
Building Mac Release macosx cocos2dx-prebuilt...
```


Previously

```
Writing build log to: /usr/local/lib/node_modules/rapidgame/build.log
Happily prebuilding 
Copying header files...
Building Mac Debug macosx cocos2dx-prebuilt...
Build failed. Please run with --verbose or check the build log: /usr/local/lib/node_modules/rapidgame/build.log
```

**Comment by seivan** [comment]
So I had some feature ideas actually.
The ability to name prebuild binaries and install custom Cocos2d-x

So I could have the original one and my fork (that works with Xcode 7) 
```prebuild 'myFork' --s "https://......com"```
next time I just do
```prebuild 'myFork'```

How about an update as well?

**Comment by NatWeiss** [comment]
Regarding `cocos2d_libs.xcodeproj`: I see now what you meant. Yes, this will eventually need to be a pull request to the cocos2d-x team. Although I suspect they are already working it into the next release, or they already did with 3.7.1...

If it's not currently a part of an official cocos2d-x release, then it will need to be added to `src/cocos2d.patch`. I can take care of that part though.

**Comment by NatWeiss** [comment]
Regarding the forking, I can't really comment as it's something I wouldn't use. If you do end up doing it please make sure it's simple, in the spirit of RapidGame and part of a separate pull request.
