### ISSUE TITLE
Why is it building a release version for the Simulator? 

### ISSUE THREAD

**Issue by seivan** [NatWeiss/RapidGame#29]
```Building iOS Release iphonesimulator cocos2dx-prebuilt...```
I am not sure you can actually run a release version on the simulator, so it might actually be a redudant step, but I might be wrong.

**Comment by NatWeiss** [comment]
Hmm, good point. Simulator + release step should be skipped.

**Comment by NatWeiss** [comment]
Added to "to do" list.
