### ISSUE TITLE
Windows prerequisutes

### ISSUE THREAD

**Issue by drawable** [NatWeiss/RapidGame#31]
You should add to the windows prerequisites that the build tools need to be installed as well. I know zero about Windows development so there might be a better way. What I did was.

Install VS Community 2015
rapidgame
create a new game

Error message saying something like "Write the path to the lib.exe into file..."

Couldn't find lib.exe. So I opened the solution rapidgame created and VS started downloading lots of stuff for WinXP targets, other things and the build tools. After that lib.exe was present in the bin folder of VS.

Now it is prebuilding, but prebuild fails. Need to invesitgate further. Will submit new issues for what I find

**Comment by NatWeiss** [comment]
Thanks, I've added a bullet point to the [Windows Notes](https://github.com/natweiss/rapidgame#windows-notes).
