### ISSUE TITLE
Prebuild for Cocos2d fails when working on a clean Windows install

### ISSUE THREAD

**Issue by drawable** [NatWeiss/RapidGame#32]
Installed rapidgame and VS Commuity 2015.

Prebuild fails.

Error deleting symlink: Error: ENOENT, no such file or directory 'C:\Program Files\nodejs\node_modules\rapidgame\latest'

And
Building Windows Debug cocos2d-js-win32.sln...
Build failed. Please run with --verbose or check the build log: C:\Program Files\nodejs\node_modules\rapidgame\build.log

build.log says

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Program Files\nodejs\node_modules\rapidgame\src\cocos2d-x\external\Box2D\proj.win32\libbox2d.vcxproj]

So I opened the solution cocos2d-js-win32.sln in VS and built it from within the IDE. No problems.

**Comment by NatWeiss** [comment]
Usually this happens when you forget to run your commandline as administrator (as mentioned in the readme).

If you *did* run as administrator, then feel free to re-open this issue.

**Comment by drawable** [comment]
I definetely ran everything as an administrator.
