### ISSUE TITLE
Header directory references missing on VS and XCode projects

### ISSUE THREAD

**Issue by drawable** [NatWeiss/RapidGame#34]
The projects miss references to the following header dirs in order to compile:

..\lib\cocos2d\x\include\cocos\scripting\js-bindings\auto
..\lib\cocos2d\x\include\cocos\scripting\js-bindings\manual

Also for XCode iOs targets there are missing all the header files for the Cocos2Dx plugin-system somwhere in the lib folder.

**Comment by NatWeiss** [comment]
Which engine (cocos2d-x or cocos2d-js) and platform (Mac, Windows, iOS, Android) are missing those header dirs?

**Comment by drawable** [comment]
Engine is cocos2d-js, platforms I tested are Windows, Mac and iOS.
