### ISSUE TITLE
Build mac target does not work. Cocos misses files

### ISSUE THREAD

**Issue by drawable** [NatWeiss/RapidGame#35]
fter doing just 

rapidgame create cocos2djs "Nme" id

and building (after adding header search paths, se issue #34). The build succeeds but when running I get the following error message:

cocos2d: fullPathForFilename: No file found at script/jsb_boot.jsc. Possible missing file.
jsb: ERROR: File /Users/stephan/Library/Developer/RapidGame/src/cocos2d-x/cocos/scripting/js-bindings/manual/localstorage/js_bindings_system_functions.cpp: Line: 65, Function: JSB_localStorageSetItem
Error processing arguments
JS: /Users/stephan/Library/Developer/Xcode/DerivedData/Test-grcaubmdrulrctcibswjgppgawkw/Build/Products/Debug/Test.app/Contents/Resources/Assets/lib/Game.js:336:Error: Error processing arguments

(evaluatedOK == JS_FALSE)

**Comment by NatWeiss** [comment]
Sorry the cocos2d-js template is out of date.
