### ISSUE TITLE
Prevent Rapidgame from downloading cocos2dx

### ISSUE THREAD

**Issue by im-amirali** [NatWeiss/RapidGame#36]
Hello ,

i just wanted to make a project using rapidgame but i dont want it download the latest cocos2dx 
because i already did ,
my question is how can i set cocos2dx path inside rapidgame ,

i have latest cocos2dx.

**Comment by NatWeiss** [comment]
Easiest way is to allow it to download and extract cocos2d-x, then just replace the `src/cocos2d-x` folder with whatever version you like.

**Comment by NatWeiss** [comment]
If you don't want to download, you can also create the file `src/downloaded.txt` and give it the contents of the URL that your version of RapidGame wants to download (see the top of `rapidgame.js`). If it already has the `src/downloaded.txt` file and it matches the URL, then it won't download again.
