### ISSUE TITLE
Link error running the Windows project solution on VS12.0 (2013)

### ISSUE THREAD

**Issue by rmallermartins** [NatWeiss/RapidGame#38]
I successfully prebuilt the Windows Debug and Release versions with rapidgame, created a project using rapidgame and opened the solution on Visual Studio 12.0 (2013), but when I try to build it (Debug or Release), I get the following errors:  

* `Error 1 error LNK2001: unresolved external symbol __imp____acrt_iob_func	C:\Users\rmall\Desktop\teste\Projects\windows\libcocos2dx-prebuilt.lib(chipmunk.obj)	teste`
* `Error 2 error LNK2001: unresolved external symbol __imp____stdio_common_vfprintf	C:\Users\rmall\Desktop\teste\Projects\windows\libcocos2dx-prebuilt.lib(chipmunk.obj)	teste`

I was just so close, and then this happens to me (cries a lot T-T), can anyone help me with this?

**Comment by NatWeiss** [comment]
Awww. Sorry man! I would try VS 2015. If that doesn't work then check out cocos2d-x' new [gen-libs](http://www.cocos2d-x.org/wiki/Cocos_gen-libs) command. I haven't tried it yet but it might make RapidGame obsolete.

**Comment by rmallermartins** [comment]
Today I'll try using Windows 10 SDK, I'm using Windows 10, but VS12 only comes with Windows 7 or 8 SDKs, if that doesn't work, will try your suggetions. Big fan from Brazil Nat!

**Comment by NatWeiss** [comment]
Hello! :)

**Comment by rmallermartins** [comment]
Decided to directly download VS2015 and give the gen-libs a try, since I work full time and I use a 5 years old Notebook, it'll be a bit slow process. But if you want, I can test if those errors will still continue using VS2015 (can't test with VS2013 anymore, since I already uninstalled it...).

**Comment by NatWeiss** [comment]
No worries! Enjoy dev.
