### ISSUE TITLE
unable to find lib.exe path  in windows

### ISSUE THREAD

**Issue by johnramesh** [NatWeiss/RapidGame#39]
I am also set the path in directory of roaming/npm/node_modules/rapidgame/libexepath.txt as 

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin

but it gives the following error.

![builderror](https://cloud.githubusercontent.com/assets/1014015/10618197/40ddb0a0-778c-11e5-8dee-f432fe4236b4.png)

**Comment by NatWeiss** [comment]
Are you sure you got those paths correct? It looks like it finds your MSBuild.exe in the 14.0 folder which is VS 2015. But you have specified the 10.0 folder in the above path which corresponds to VS 2010.

If you have further troubles I recommend taking a look at cocos2d-x new [gen-libs](http://www.cocos2d-x.org/wiki/Cocos_gen-libs). It might have already made RapidGame obsolete.

**Comment by johnramesh** [comment]
Yes it is correct.Still it does not take the path.
I see in updates as ,
August 11, 2015: On Windows, the path to MSBuild.exe, Lib.exe and VCTargetsPath can be set manually in case they cannot be automatically located.

How can I set these paths manually.is there any information to that.
Because I already set path for lib.exe in libexepath.text in rapidgame node_module,but not works.

**Comment by johnramesh** [comment]
I find the issue,in rapidgame.js file a function for getting libpath as "getLibExePath".In that checking file,but we provide path only as " if (fileExists(libExePath)) " as passed whole file path it is executed successfully.Thats fine,but after completing the project it shows the error as follows,

Build FAILED.

       "C:\Users\johnramesh\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-x\build\cocos2d-js-win32.sln" (libcocos2d;libjscocos2d target) (1) ->
       "C:\Users\johnramesh\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-x\cocos\2d\libcocos2d.vcxproj" (default target) (2) ->

         C:\Users\johnramesh\AppData\Roaming\npm\node_modules\rapidgame\src\cocos2d-x\cocos\2d\libcocos2d.vcxproj(36,3): error MSB4019: The imported project "C:\Microsoft.Cpp.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)
I found "prebuildWin" function in rapidgame.js file in line no 754 as

// set VCTargetsPath
	// (overcome error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found.)
	process.env["VCTargetsPath"] = vcTargetsPath;

is there any issue here or in my System.

Thanks for looking...

**Comment by NatWeiss** [comment]
Sorry, can you post your code for fixing `getLibExePath`?

**Comment by NatWeiss** [comment]
In regards to the props issue, you either need to let it run the complete git diff when downloading cocos2d-x or else manually change your `cocos\2d\cocos2dx.props` file [like this](https://github.com/NatWeiss/RapidGame/blob/ddbc1a968756f681a3c35ca0bfff297b1b3e0f1f/src/cocos2d.patch).

**Comment by johnramesh** [comment]
I installed VS 2015 community version it solves the problem.

But android prebuild fails,It show the following error

MSBUILD: C:\Program Files (x86)\MSBuild\14.0\bin\amd64\MSBuild.exe
LIB: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\lib.exe
VCTARGETS: C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\
Happily prebuilding android
Building Android libraries for all platforms...

Spawning:
	make 

Current dir:
	C:\Program Files\nodejs\node_modules\rapidgame\src\proj.android


./build.sh armeabi Debug

PLATFORM=android-14

ARCH=armeabi
CONFIG=Debug
CORES=4

CC_ROOT=/c/Program Files/nodejs/node_modules/rapidgame/src/cocos2d-x

NDK_MODULE_PATH=/c/Program Files/nodejs/node_modules/rapidgame/src/cocos2d-x:/c/Program Files/nodejs/node_modules/rapidgame/src/cocos2d-x/external:/c/Program Files/nodejs/node_modules/rapidgame/src
NDK_TOOLCHAIN_VERSION=4.9

/c/cygwin64/bin/awk: /c/cygwin64/bin/awk: cannot execute binary file

c:/CoCoS-Devlopment/android-ndk-r10e/build/core/init.mk:373: *** Android NDK: Aborting.    .  Stop.

/usr/bin/which: no Android NDK: Host 'awk' tool is outdated. Please define NDK_HOST_AWK to point to Gawk or Nawk !    ar in (/usr/local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/100/Tools/Binn:/cygdrive/c/Program Files/Microsoft SQL Server/100/Tools/Binn:/cygdrive/c/Program Files/Microsoft SQL Server/100/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/100/Tools/Binn/VSShell/Common7/IDE:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/100/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/PrivateAssemblies:/cygdrive/c/Program Files (x86)/Microsoft ASP.NET/ASP.NET Web Pages/v1.0:/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Program Files/Microsoft/Web Platform Installer:/cygdrive/c/Program Files (x86)/GtkSharp/2.12/bin:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/msys/1.0/bin:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Users/johnramesh/.dnx/bin:/cygdrive/c/Program Files/Microsoft DNX/Dnvm:/cygdrive/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/cygdrive/c/CoCoS-Devlopment/cocos2d-js-v3.6.1/cocos2d-js-v3.6.1/tools/cocos2d-console/bin:/cygdrive/c/Python27:/cygdrive/c/Ruby21/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_60/bin:/cygdrive/c/apache-ant-1.9.4-bin/apache-ant-1.9.4/bin:/cygdrive/c/adt-bundle-windows-x86_64-20140702/sdk/platform-tools:/cygdrive/c/adt-bundle-windows-x86_64-20140702/sdk/tools:/cygdrive/c/adt-bundle-windows-x86_64-20140702/sdk/build-tools/19.0.0:/cygdrive/c/CoCoS-Devlopment/android-ndk-r10e:/cygdrive/c/Users/johnramesh/AppData/Roaming/npm)

Missing the 'ar' NDK build tool. Please install the Android NDK and toolchains.

make: *** [all] Error 1

In stackoverflow thread 
http://stackoverflow.com/questions/8384213/android-ndk-revision-7-host-awk-tool-is-outdated-error

I did like the above thread but not worked.

Guide me to further.Thanks

**Comment by johnramesh** [comment]
1. android-ndk-r10e  is the problem.I installed android-ndk-r9d.It works.

2.In cygwin , white spaces in path does not take so I put environment variables for path which contains "Program Files" as "Progra~1", because My Machine is 64-bit version.

3.Prebuild is succeeded.

4.After creating the project,with out any modifications I fired the command "make",build fails.

The Following error came.
![errormake](https://cloud.githubusercontent.com/assets/1014015/10738062/85db5b22-7c3b-11e5-91c8-f9b3394f01aa.png)

I am awaiting for your reply.

Thank you very much.

**Comment by NatWeiss** [comment]
Sorry man, I really haven't tried the Windows + Android build. Another developer got that all working. Maybe try [gen-libs](http://www.cocos2d-x.org/wiki/Cocos_gen-libs) instead of RapidGame?

**Comment by rmallermartins** [comment]
@johnramesh, I was having some trouble making it work on Windows too, tried the gen-libs and it worked on first. This guy wrote a quick guide on how to make it work for the win32 VS 2015 build, worked for me ;) http://discuss.cocos2d-x.org/t/prebuilt-for-win32-cocos-gen-libs-p-win32/24497.

The bad part, is that it doesn't have a template project (yet), so you have to create a new project, delete the cocos2d folder inside it, and make the necessary changes for each platform specific project for targeting the prebuilt lib.

**Comment by NatWeiss** [comment]
The new Android prebuild command is greatly simplified in RapidGame 1.0.0. It can even be run with a command prompt instead of cygwin. Hopefully this issue is solved. If not, go ahead and re-open or open a new issue.
