### ISSUE TITLE
Xcode project file can't be parsed.

### ISSUE THREAD

**Issue by erichocean** [NatWeiss/RapidGame#4]
I tried this today on Mac OS X with Xcode 6. I installed globally via npm, and then use the following command:

    rapidgame create cocos2dx "Heck Yeah" org.myorg.heckyeah

After pre-building the binaries, found the Xcode project and double-clicked. The error Xcode gives me is:

    Project /Volumes/XyDev/code/Heck Yeah/Projects/Heck Yeah.xcodeproj cannot be opened because the project file cannot be parsed.

Any ideas?

**Comment by erichocean** [comment]
On a whim, I tried with the name "HeckYeah" (no space). That Xcode project opened fine.

**Comment by NatWeiss** [comment]
Ahh. That's exactly what I was going to suggest. Glad it works without the space. I did have that working a few releases ago but must have broken it again. Will fix for the next release. Thanks for mentioning!
