### ISSUE TITLE
Configure cocos2d-x version number

### ISSUE THREAD

**Issue by jgod** [NatWeiss/RapidGame#40]
Trying to migrate existing project on `3.7.1` to use prebuilts with this. Are there plans for setting a version manually, like with a flag? I see that it's hardcoded into urls and the makefile

**Comment by jgod** [comment]
Discovered that all I have to do is replace `rapidgame/src/cocos2d-x` with mine, but I'll leave this open for a bit since the feature seems solid to me, even if that means only supporting a limited range of versions like (3.7 - 3.8 or whatever) at any time, since the cocos folder structure changes aggressively.

**Comment by NatWeiss** [comment]
Glad you discovered this. :) Will make it clearer that it is possible on the readme.

**Comment by NatWeiss** [comment]
The latest version 1.0.0 you can now specify a cocos2d-x source folder with the --src option.
