### ISSUE TITLE
ios didn`t prebuild

### ISSUE THREAD

**Issue by sherbachuk** [NatWeiss/RapidGame#42]
I have an error in xcode: 
warning: directory not found for option '-L/Users/artem/Desktop/test/Projects/../lib/cocos2d/x/lib/Debug-iOS/iphonesimulator'

When I do 'rapidgame prebuild --verbose' I have got an error:

error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib/libsqlite3.dylib (No such file or directory)

=== BUILD TARGET libjscocos2d Mac OF PROJECT cocos2d_js_bindings WITH CONFIGURATION Debug ===

Check dependencies

** BUILD FAILED **

The following build commands failed:
	Libtool /Users/artem/Library/Developer/Xcode/DerivedData/cocos2dx-prebuilt-advwimtjrpvobacnuatawumfzguv/Build/Products/Debug/libcocos2d\ Mac.a normal x86_64
(1 failure)

Can anybody help please. RapiGame -v 0.9.12

**Comment by TomLinthwaite** [comment]
I have the same problem. I guess you could open the project (cocos2dx-prebuilt.xcodeproj) and remove the references to sqlite3.dylib but not 100% sure that won't break anything.

**Comment by 1taypan** [comment]
The problem was solved. 
I did prebuilt only for ios "rapidgame prebuild ios". 
Be patient, because it will take a long time. 
When it all finished you can check: 
/Users/ "your user name"/Library/Developer/RapidGame/0.9.12/cocos2d/x/lib/  
"Debug-iOS" and "Release-iOS" folders if it there then all fine.

**Comment by TomLinthwaite** [comment]
How was it solved? I tried to prebuild it just a second ago and I got the same error. I edited the project like I said and it worked. Seems with the new xcode 7 .dylib files are no longer supported?

**Comment by NatWeiss** [comment]
If it's not too much trouble, please try with the latest 1.0.0 version of RapidGame. Feel free to re-open this issue.
