### ISSUE TITLE
Android windows build process

### ISSUE THREAD

**Issue by aeacusvol** [NatWeiss/RapidGame#44]
I have followed the android setup tutorial but when trying to build android on windows using Cygwin i was getting lots of errors with the ${sdk.dir} route. I included it in a local.properties file as well but no luck. I have to replace all references to the route with the hard coded path to to get to the ant -check-env part but im now getting the following error which suggests my path isn't getting escaped correctly. Have some how missed a vital step? Does anyone have any suggestions of what i can try or any more information i can provide?

```C:\Users\dev\AppData\Local\Android\sdk\tools\ant\build.xml:397: SDK Location 'C:UsersdevAppDataLocalAndroidsdk' is not valid.```

**Comment by NatWeiss** [comment]
Sorry, not sure how to help you here.
