### ISSUE TITLE
'"undefinedlib.exe"' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by blazer044** [NatWeiss/RapidGame#7]
I can't prebuild rapidgame. That's error from build log

'"undefinedlib.exe"' is not recognized as an internal or external command, operable program or batch file.

I installed git, node, python , turned off antivirus , ran cmd as administator and tried to install rapidgame again, but its not working still.
I cant find anything in google.
What should i do?

**Comment by NatWeiss** [comment]
It's unable to find your Visual C++ bin directory. This is usually C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\.

You can fix this yourself by editing rapidgame.js line 1007. At the end of the getVCBinDir() function just add this:

`return "\\path\\to\\your\\vc\\bin\\";`

Make sure to replace "\" with "\\" in the path.

Please Let me know how it goes (also where your VC bin dir is) so I can fix the bug and it will magically work next time.

**Comment by blazer044** [comment]
It prebuilds now :) Thank you.
my VC bin dir is : D:\Programs\Microsoft Visual Studio 12.0\VC\bin

But i have another problem now, when im trying to build a solution.

error LNK2001: unresolved external symbol "public: virtual void __thiscall MenuScene::onEnter(void)" (?onEnter@MenuScene@@UAEXXZ)	C:\Users\Blazer\Desktop\HeckYeah\Projects\windows\AppDelegate.obj	HeckYeah

error LNK2019: unresolved external symbol "void __cdecl Game::setContentRect(class cocos2d::Rect const &)" (?setContentRect@Game@@YAXABVRect@cocos2d@@@Z) referenced in function "public: virtual bool __thiscall AppDelegate::applicationDidFinishLaunching(void)" (?applicationDidFinishLaunching@AppDelegate@@UAE_NXZ)	C:\Users\Blazer\Desktop\HeckYeah\Projects\windows\AppDelegate.obj	HeckYeah

I googled it and i know it's problem with linker.
Which libs i have to add to Additional Dependencies?

That's automatically added libs
libcocos2dx-prebuilt.lib
opengl32.lib
ws2_32.lib
winmm.lib

**Comment by NatWeiss** [comment]
It looks like you are building the new cocos2d-x template as opposed to the cocos2d-js template, right?

I think I may have forgotten to add a few files to the Windows cocos2d-x template. Do you have these files in your solution?

Game.h / Game.cpp
GameScene.h / GameScene.cpp
MenuScene.h / MenuScene.cpp

If not, please add them to your project / solution.

**Comment by NatWeiss** [comment]
I just confirmed that I did forget to add those files to the Windows project. So adding them should definitely help. Got it fixed for the next version though. Let me know if you encounter any bugs compiling after adding those files.
