### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by jonnyijapan** [NatWeiss/RapidGame#8]
Sorry for the extreme beginner question, but as I am a beginner of cocos2d-x, and have just used "rapidgame create blabla.." to create a game, how do I subsequently run+launch the android target (or any of the other targets)?

Some quick advice on this in the readme would be very helpful to get going. Seeing as the cocos2dx docs leave a lot out...

**Comment by NatWeiss** [comment]
Plug your device in then:
`
cd Projects/android
make
make run
`

Also, if it's your first time running an app on Android you will need to [get things set up](http://developer.android.com/tools/device.html).

**Comment by jonnyijapan** [comment]
Thanks, I got it going. However for some reason make run installs the binary into the device, but I had to tap the icon myself on device to bring it up.

**Comment by NatWeiss** [comment]
Yep, that's how it works. If you run it from Eclipse I think it will actually run it on the device for you.
