### ISSUE TITLE
upgrading to 0.9.7 from 0.9.5 introduces build errors in AppDelegate.cpp

### ISSUE THREAD

**Issue by nanocore** [NatWeiss/RapidGame#9]
I have a project built using rapidgame 0.9.5 and upgraded to 0.9.7.  I prebuilt and updated lib in my project and quit Xcode.  Started Xcode (using 6.1.1) back up and tried to build and the resultant errors 

iOS Group
.../Projects/AppDelegate.cpp
.../Projects/AppDelegate.cpp:35:2: Reference to 'Size' is ambiguous
.../Projects/AppDelegate.cpp:37:3: Use of undeclared identifier 'designRes'
.../Projects/AppDelegate.cpp:39:3: Use of undeclared identifier 'designRes'
.../Projects/AppDelegate.cpp:42:25: Use of undeclared identifier 'designRes'
.../Projects/AppDelegate.cpp:45:22: Use of undeclared identifier 'designRes'
.../Projects/AppDelegate.cpp:46:15: No member named 'origin' in 'Rect'
.../Projects/AppDelegate.cpp:46:27: Use of undeclared identifier 'designRes'
.../Projects/AppDelegate.cpp:46:57: No member named 'size' in 'Rect'
.../Projects/AppDelegate.cpp:48:3: Use of undeclared identifier 'designRes'
.../Projects/AppDelegate.cpp:49:15: No member named 'origin' in 'Rect'
.../Projects/AppDelegate.cpp:49:27: Use of undeclared identifier 'designRes'
.../Projects/AppDelegate.cpp:49:58: No member named 'size' in 'Rect'
.../Projects/AppDelegate.cpp:56:53: Use of undeclared identifier 'designRes'

**Comment by NatWeiss** [comment]
What project is this: cocos2dx or cocos2djs?

Have you tried adding `using cocos2d::Size;` to your AppDelegate.h?

**Comment by nanocore** [comment]
Yes u made the changes to get it complied but thought it might be an issue for when someobe generates a new project. I thought that this was part of the templated code.
